id: IAC471E3B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-11T09:13:55+00:00'
last_modified: '2022-06-09T17:59:01.043887+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23871
  title: སྒྲུབ་པ་ཉམས་སུ་བླང་བའི་ལག་ལེན་དགོས་འདོད་འབྱུང་བའི་གཏེར་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    517F:
      image_group_id: I3608
      title: ''
      total_pages: 602
      order: 1
      base_file: 517F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
